apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/epig
namePrefix: dev-
namespace: dev-epig
patches:
  - target:
      kind: HelmRelease
      name: epig
      group: helm.toolkit.fluxcd.io
      version: v2beta1
    patch: |-
      - op: replace
        path: /spec/chart/spec/valuesFiles
        value:
          - ./helm/epig/values.yaml
          - ./helm/epig/values/values-dev.yaml
---
