# TEST values for layers-db-etl.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  tag: main.52edb14.1
  usePullSecret: false
  pullSecretName: none

replicas: 2
envName: test
ingressHost: test-layers-db-etl.k8s-01.konturlabs.com

createResource:
  defaultSecrets: false
  ingress: true
  prometheusRule: false
  serviceMonitor: false
  deploymentLivenessProbe: true
isOfflineInstallation: false
probeInitialDelaySeconds: 15

pgHost: london.k8s-01.kontur.io

alertingTime: 5m