# QUICKSTART values for layers-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  tag: main.52edb14.1
  usePullSecret: true
  pullSecretName: nexus8084

replicas: 1
envName: quickstart
ingressHost: layers-db-etl.kontur

createResource:
  defaultSecrets: true
  ingress: true
  prometheusRule: false
  serviceMonitor: false
  deploymentLivenessProbe: true
isOfflineInstallation: true
probeInitialDelaySeconds: 90

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 768Mi