{{ if ne .Values.envName "local" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.envName }}-event-api
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: event-api
    app.kubernetes.io/instance: {{ .Values.envName }}-event-api
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    cert-manager.io/cluster-issuer: letsencrypt-staging #use letsencrypt-staging for testing
    acme.cert-manager.io/http01-edit-in-place: "true" #required otherwise ACME challenge can't be completed
    nginx.org/client-max-body-size: 5m
spec:
  tls:
    - hosts:
        - {{ .Values.envName }}-event-api.k8s-01.konturlabs.com
      secretName: {{ .Values.envName }}-event-api-tls # < cert-manager will store the created certificate in this secret.
  ingressClassName: nginx
  rules:
    - host: {{ .Values.envName }}-event-api.k8s-01.konturlabs.com
      http:
        paths:
          - path: /events
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.envName }}-event-api
                port:
                  name: main
---
{{ end }}