{{ if .Values.createResource.defaultSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.envName }}-event-api
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: event-api
    app.kubernetes.io/instance: {{ .Values.envName }}-event-api
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  AWS_ACCESS_KEY_ID: cGFzc3dvcmQ= # = password #TODO disable
  AWS_SECRET_KEY: cGFzc3dvcmQ= # = password #TODO disable
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ= # = password
  emdat.password: cGFzc3dvcmQ= # = password #TODO disable
  pdc.password: cGFzc3dvcmQ= # = password #TODO disable
  spring.redis.password: cGFzc3dvcmQ= # = password
---
apiVersion: v1
kind: Secret
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: event-api-redis
    app.kubernetes.io/instance: {{ .Values.envName }}-event-api-redis
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  redis-password: cGFzc3dvcmQ= # = password
---
{{ end }}
