{{ if .Values.createDefaultSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.envName }}-layers-tiles-api
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: layers-tiles-api
    app.kubernetes.io/instance: {{ .Values.envName }}-layers-tiles-api
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL2xheWVycy10aWxlcy1hcGk6cGFzc3dvcmRAZG9ja2VyLmZvci5tYWMuaG9zdC5pbnRlcm5hbC9sYXllcnMtZGI= # = postgresql://layers-tiles-api:password@docker.for.mac.host.internal/layers-db #TODO non-mac specific?
---
{{ end }}