---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.envName }}-layers-tiles-api
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: layers-tiles-api
    app.kubernetes.io/instance: {{ .Values.envName }}-layers-tiles-api
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: layers-tiles-api
    app.kubernetes.io/instance: {{ .Values.envName }}-layers-tiles-api
    #don't add app.kubernetes.io/version
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  ports:
  - name: lrs-tiles-api
    port: {{ .Values.HttpPort }}
    targetPort: lrs-tiles-api
    protocol: TCP
---

