apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.envName }}-layers-api
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: layers-api
    app.kubernetes.io/instance: {{ .Values.envName }}-layers-api
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  spring.datasource.url: 'jdbc:postgresql://{{ .Values.databaseHost }}:{{ .Values.databasePort }}/layers-db'
  spring.datasource.username: layers-api
  spring.security.oauth2.resourceserver.jwt.issuer-uri: {{ .Values.jwtIssuerUri }}
  spring.security.oauth2.resourceserver.jwt.jwk-set-uri: {{ .Values.jwtJwkSetUri }}
---
#create manually, not managed by Helm as it's a secret
#apiVersion: v1
#kind: Secret
#metadata:
#  name: {{ .Values.envName }}-layers-api
#  namespace: {{ .Release.Namespace }}
#labels:
#  app.kubernetes.io/name: layers-api
#  app.kubernetes.io/instance: {{ .Values.envName }}-layers-api
#  stage: {{ .Values.envName }}
#data:
***REMOVED***
---