{{ if ne .Values.envName "local" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.envName }}-layers-api
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: layers-api
    app.kubernetes.io/instance: {{ .Values.envName }}-layers-api
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    cert-manager.io/cluster-issuer: letsencrypt-production #use letsencrypt-staging for testing
    acme.cert-manager.io/http01-edit-in-place: "true" #required otherwise ACME challenge can't be completed
    nginx.org/client-max-body-size: 5m
    nginx.org/server-snippets: |
      client_max_body_size 5m;

spec:
  tls:
    - hosts:
        - {{ .Values.envName }}-layers-api.k8s-01.konturlabs.com
      secretName: {{ .Values.envName }}-layers-api-tls # < cert-manager will store the created certificate in this secret.
  ingressClassName: nginx
  rules:
    - host: {{ .Values.envName }}-layers-api.k8s-01.konturlabs.com
      http:
        paths:
          - path: /layers/v2/
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.envName }}-layers-api
                port:
                  name: main
---
{{ end }}
