apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Values.envName }}-layers-api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: layers-api
    stage: {{ .Values.envName }}
  name: {{ .Values.envName }}-layers-api
  namespace: {{ .Release.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: main
      port: {{ .Values.port }}
      protocol: TCP
      targetPort: main
    - name: management
      port: {{ .Values.management.port }}
      protocol: TCP
      targetPort: management
  selector:
    app.kubernetes.io/instance: {{ .Values.envName }}-layers-api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: layers-api
    stage: {{ .Values.envName }}
  sessionAffinity: None
  type: ClusterIP