{{ if .Values.createResource.serviceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Values.envName }}-layers-api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: layers-api
    stage: {{ .Values.envName }}
  name: {{ .Values.envName }}-layers-api
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: management
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.envName }}-layers-api
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: layers-api
      stage: {{ .Values.envName }}
{{ end }}