apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/titiler
namePrefix: dev-
namespace: dev-titiler
patches:
  - target:
      kind: HelmRelease
      name: titiler
      group: helm.toolkit.fluxcd.io
      version: v2beta1
    patch: |-
      - op: replace
        path: /spec/chart/spec/valuesFiles
        value:
          - ./helm/titiler/values.yaml
          - ./helm/titiler/values/values-dev.yaml
