createResource:
  defaultSecrets: false
  ingress: true

ENV_NAME: prod
SITE_URL: https://disaster.ninja/active/
APP_ID: 'c5ecc65b-1e7e-4e31-92a4-222fadeaeef0'
TIMEOUT: 9000
CACHE_TTL: 3600
DEBUG: FALSE
DEFAULT_IMAGE_URL: "https://disaster.ninja/active/static/assets/preview_screenshot.png"

containers:
  pullSecretName: none
  usePullSecret: false
  chromium_headless:
    replicas: 1
    tag: "release-1.1.0.00d41e5.1"
  preview_generator:
    replicas: 1
    tag: "release-1.1.0.00d41e5.1"
  redis:
    replicas: 1
    tag: "7-alpine3.16"
