createResource:
  defaultSecrets: true
  ingress: false

ENV_NAME: quickstart
SITE_URL: https://test-apps-ninja02.konturlabs.com/active/ #TODO local DN
APP_ID: 'f29339bd-8049-41ae-9d6b-f726d8451894'
TIMEOUT: 60000
CACHE_TTL: 1
DEBUG: TRUE

containers:
  pullSecretName: nexus8084
  usePullSecret: true
  chromium_headless:
    replicas: 1
    tag: "release-1.1.0.00d41e5.1"
  preview_generator:
    replicas: 1
    tag: "release-1.1.0.00d41e5.1"
  redis:
    replicas: 1
    tag: "7-alpine3.16"
resources:
  chromium:
    requests:
      cpu: 100m