---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.envName }}-insights-api
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: insights-api
    app.kubernetes.io/instance: {{ .Values.envName }}-insights-api
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: insights-api
    app.kubernetes.io/instance: {{ .Values.envName }}-insights-api
    #don't add app.kubernetes.io/version
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  ports:
    - name: main
      port: {{ .Values.port }}
      targetPort: main
      protocol: TCP
    - name: management
      port: {{ .Values.management.port }}
      targetPort: management
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.envName }}-insights-api-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: insights-api-redis
    app.kubernetes.io/instance: {{ .Values.envName }}-insights-api-redis
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: insights-api-redis
    app.kubernetes.io/instance: {{ .Values.envName }}-insights-api-redis
    #don't add app.kubernetes.io/version
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  ports:
    - name: main
      port: 6379
      targetPort: 6379
      protocol: TCP
    - name: metrics
      port: 9121
      targetPort: 9121
      protocol: TCP
---