# Default values for insights-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag: latest
  tagType: ""
  name: nexus.kontur.io:8084/konturdev/insights-api
  usePullSecret: true
  pullSecretName: nexus8084

port: 8625
replicas: 1
envName: local

createResource:
  defaultSecrets: false
  ingress: false
  prometheusRule: false
  serviceMonitor: false
  deploymentLivenessProbe: false

resources:
  app:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi
  redis:
    requests:
      cpu: 100m
      memory: 512M
    limits:
      memory: 1G

readinessProbe:
  initialDelaySeconds: 30

databaseHost: host.docker.internal
databasePort: 8900
jmxEnabled: true
alertingTime: 10m

keycloakUrl: 'https://keycloak01.konturlabs.com/auth'
keycloakRealm: dev

otlpTracesExporter: none
otlpTracesPort: 4317

client_max_body_size: 5g