apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.envName }}-disaster-ninja-be
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: disaster-ninja-be
    app.kubernetes.io/instance: {{ .Values.envName }}-disaster-ninja-be
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: disaster-ninja-be
      app.kubernetes.io/instance: {{ .Values.envName }}-disaster-ninja-be
      #don't add app.kubernetes.io/version
      app.kubernetes.io/managed-by: "Helm"
      stage: {{ .Values.envName }}
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: disaster-ninja-be
        app.kubernetes.io/instance: {{ .Values.envName }}-disaster-ninja-be
        app.kubernetes.io/version: {{ .Chart.Version }}
        app.kubernetes.io/managed-by: "Helm"
        stage: {{ .Values.envName }}
      annotations:
        meta.helm.sh/release-name: {{ .Release.Name }}
        meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    spec:
      containers:
      - name: disaster-ninja-be
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 8627
        resources:
          requests:
            cpu: "1"
            memory: "2G"
        {{ if eq .Values.envName "prod" }}
          limits:
            memory: "4G"
        {{ else }}
        #resource limits are not specified for non-prod stages so that they have lower priority
        {{ end }}
        env:
          - name: JAVA_TOOL_OPTIONS
            value: "-XX:MaxRAMPercentage=50"
        envFrom:
        - configMapRef:
            name: {{ .Values.envName }}-disaster-ninja-be
        - secretRef:
            name: {{ .Values.envName }}-disaster-ninja-be
        readinessProbe:
          httpGet:
            path: /active/api/health/readiness
            port: {{ .Values.service.port }}
          failureThreshold: 1
          periodSeconds: 30
          initialDelaySeconds: 5
---