{{ if .Values.createResource.defaultSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.envName }}-disaster-ninja-be
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: disaster-ninja-be
    app.kubernetes.io/instance: {{ .Values.envName }}-disaster-ninja-be
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
    kontur.platform.keycloak.username: dXNlcm5hbWVAbWFpbC5jb20= # = 'username@mail.com' #TODO this user has to be manually created and setup in keycloak
    kontur.platform.keycloak.password: cGFzc3dvcmQ= # = 'password'
    notifications.slackWebHook: bm9uZQ== # = 'none'
---
{{ end }}