apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.envName }}-titiler
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: titiler
    app.kubernetes.io/instance: {{ .Values.envName }}-titiler
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: backend
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      #don't add app.kubernetes.io/version
      app.kubernetes.io/name: titiler
      app.kubernetes.io/instance: {{ .Values.envName }}-titiler
      app.kubernetes.io/component: backend
      stage: {{ .Values.envName }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: titiler
        app.kubernetes.io/instance: {{ .Values.envName }}-titiler
        app.kubernetes.io/managed-by: "Helm"
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: backend
        stage: {{ .Values.envName }}
      annotations:
        meta.helm.sh/release-name: {{ .Release.Name }}
        meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    spec:
      containers:
        - name: titiler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
          {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.env.PORT }}
              protocol: TCP
          {{ if .Values.createResource.deploymentLivenessProbe }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            failureThreshold: 10
            periodSeconds: 15
            initialDelaySeconds: 15
          {{ end }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            failureThreshold: 1
            periodSeconds: 15
            initialDelaySeconds: 15
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}

