apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.envName }}-titiler
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: titiler
    app.kubernetes.io/instance: {{ .Values.envName }}-titiler
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: backend
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    #don't add app.kubernetes.io/version
    app.kubernetes.io/name: titiler
    app.kubernetes.io/instance: {{ .Values.envName }}-titiler
    app.kubernetes.io/component: backend
    stage: {{ .Values.envName }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
