{{ if .Values.createResource.serviceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.envName }}-user-profile-api
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: user-profile-api
    app.kubernetes.io/instance: {{ .Values.envName }}-user-profile-api
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - interval: 30s
      port: main
      path: /userprofile/metrics
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: user-profile-api
      app.kubernetes.io/instance: {{ .Values.envName }}-user-profile-api
      #don't add app.kubernetes.io/version
      app.kubernetes.io/managed-by: "Helm"
      stage: {{ .Values.envName }}
---
{{ end }}