kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.envName }}-osrm-restarter
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.envName }}-osrm-restarter
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: ["{{ .Values.envName }}-osrm-backend"]
    verbs: ["get", "patch", "list", "watch"]
---
# bind the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.envName }}-osrm-restarter
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.envName }}-osrm-restarter
subjects:
  - kind: ServiceAccount
    name: {{ .Values.envName }}-osrm-restarter
    namespace: {{ .Release.Namespace }}