---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.envName }}-osrm-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: osrm-backend
    app.kubernetes.io/instance: {{ .Values.envName }}-osrm-backend
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: osrm-backend
    app.kubernetes.io/instance: {{ .Values.envName }}-osrm-backend
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  ports:
    - name: main
      port: {{ .Values.osrmBackendPort }}
      targetPort: main
      protocol: TCP
