# Default values for disaster-ninja-be.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  be:
    repository: ghcr.io/konturio/disaster-ninja-be
    pullPolicy: Always
    tag: latest

service:
  port: 8627

envName: local

keycloakUrl: 'https://keycloak01.konturlabs.com/auth'
keycloakRealm: dev
eventApiUrl: 'https://test-apps02.konturlabs.com/events'
kcApiUrl: 'https://test-api02.konturlabs.com/layers'
layersApiUrl: 'https://test-api02.konturlabs.com/layers/v2'
insightsApiUrl: 'https://test-apps02.konturlabs.com/insights-api'
userProfileApiUrl: 'https://test-apps02.konturlabs.com/userprofile'
tilesHost: 'https://zigzag.kontur.io'

notificationsEnabled: false
notificationsFeed: disabled
notificationsAlertUrlPattern: disabled
***REMOVED***

alertingTime: 10m
