# Prod values for titiler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 16

image:
  tag: 0.7.1

envName: prod

createResource:
  ingress: true
  deploymentLivenessProbe: true