# QUICKSTART values for titiler.
replicaCount: 1

image:
  tag: 0.7.1

envName: quickstart
ingressHost: titiler.kontur.test

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1
    memory: 768Mi