apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: osrm-pipeline
spec:
  suspend: false
  interval: 5m
  chart:
    spec:
      chart: ./helm/osrm-pipeline
      valuesFiles:
        - ./helm/osrm-pipeline/values.yaml
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: kontur-platform
        namespace: flux-system
      interval: 1m
  install:
    disableWait: true
  upgrade:
    disableWait: true
    remediation:
      remediateLastFailure: true
---