apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/disaster-ninja
namePrefix: prod-
namespace: prod-disaster-ninja
patches:
  - target:
      kind: HelmRelease
      name: disaster-ninja-be
      group: helm.toolkit.fluxcd.io
      version: v2beta1
    patch: |-
      - op: replace
        path: /spec/chart/spec/valuesFiles
        value:
          - ./helm/disaster-ninja-be/values.yaml
          - ./helm/disaster-ninja-be/values/values-prod.yaml
  - target:
      kind: HelmRelease
      name: disaster-ninja-fe
      group: helm.toolkit.fluxcd.io
      version: v2beta1
    patch: |-
      - op: replace
        path: /spec/chart/spec/valuesFiles
        value:
          - ./helm/disaster-ninja-fe/values.yaml
          - ./helm/disaster-ninja-fe/values/values-prod.yaml
---