---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.envName }}-keycloak
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: {{ .Values.envName }}-keycloak
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: {{ .Values.envName }}-keycloak
    #don't add app.kubernetes.io/version
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  ports:
  - name: main
    port: {{ .Values.service.main }}
    targetPort: main #TODO check
    protocol: TCP
  - name: management
    port: {{ .Values.service.management }}
    targetPort: management #TODO check
    protocol: TCP
---

