---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: disaster-ninja-be
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/disaster-ninja-be
      valuesFiles:
        - values.yaml
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: kontur-platform
        namespace: kontur-platform #TODO check
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
---