---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: disaster-ninja-fe
spec:
  chart:
    spec:
      chart: ./helm/disaster-ninja-fe
      interval: 1m
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: kontur-platform
        namespace: flux-system
      valuesFiles:
        - ./helm/disaster-ninja-fe/values.yaml
  interval: 5m
  suspend: false
  test:
    enable: true
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    k8s_cluster_flavor: '${k8s_cluster_flavor}' # optional value that can be substituted in a Flux pipeline