---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: disaster-ninja-fe
spec:
  suspend: false
  interval: 5m
  chart:
    spec:
      chart: ./helm/disaster-ninja-fe
      valuesFiles:
        - ./helm/disaster-ninja-fe/values.yaml
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: kontur-platform
        namespace: flux-system
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
---