# Default values for raster-tiler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag: latest
  name: nexus.kontur.io:8084/konturdev/raster-tiler

port: "80"
replicas: 1
envName: local
imagePullSecretName: nexus8085
base_url: https://local-raster-tiler.k8s-01.konturlabs.com
pg_database: layers-db
pg_host: milan.k8s-01.kontur.io
storage_size: 5Gi
