# DEV values for layers-tiles-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
envName: dev
ingressHost: dev-layers-tiles-api.k8s-01.konturlabs.com
ingressClass: ingress-nginx

replicas: 1

image:
  repository: nexus.kontur.io:8085/konturdev/pg_tileserv
  tag: 14864-downgrade-pg_tileserv-error-level-to-warning #this version will be automatically deployed by Flux

DbPoolMaxConnLifeTime: 10m
DbPoolMaxConns: 10
DbTimeout: 10
CacheTTL: 10
EnableMetrics: true
Debug: true

createResource:
  defaultSecrets: false
  ingress: true
  prometheusRule: true
  serviceMonitor: true
isOfflineInstallation: false
probeInitialDelaySeconds: 5