# TEST values for user-profile-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag: 13246-adjust-endpoint-apps-id-to-get-features-configuration-ups.752403b.1
  pullSecretName: none
  usePullSecret: false

replicas: 2
envName: test
ingressHost: test-user-profile-api.k8s-01.konturlabs.com

createResource:
  defaultSecrets: false
  ingress: true
  prometheusRule: true
  serviceMonitor: true
  deploymentLivenessProbe: false
isOfflineInstallation: false
probeInitialDelaySeconds: 15

databaseHost: london.k8s-01.kontur.io.

jwtIssuerUri: https://keycloak01.konturlabs.com/auth/realms/test
jwtJwkSetUri: https://keycloak01.konturlabs.com/auth/realms/test/protocol/openid-connect/certs

alertingTime: 5m

otlpTracesExporter: otlp
otlpTracesPort: 4317
