# TEST values for user-profile-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag: 12627-update-keycloak-spi-plugin-to-use-full-name-instead-of-first-and-last-name.c6a6163.1

replicas: 2
envName: test
databaseHost: london.k8s-01.kontur.io.

jwtIssuerUri: https://keycloak01.konturlabs.com/auth/realms/test
jwtJwkSetUri: https://keycloak01.konturlabs.com/auth/realms/test/protocol/openid-connect/certs

dnsNameOuter: test-apps.konturlabs.com
alertingTime: 5m

otlpTracesExporter: otlp
otlpTracesPort: 4317
