# DEV values for user-profile-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag: 13113-serve-application-name-and-application-logo-on-dn.4b9a799.1

replicas: 2
envName: dev

createResource:
  defaultSecrets: false
  ingress: true
  prometheusRule: true
  serviceMonitor: true

databaseHost: milan.k8s-01.kontur.io.

jwtIssuerUri: https://keycloak01.konturlabs.com/auth/realms/dev
jwtJwkSetUri: https://keycloak01.konturlabs.com/auth/realms/dev/protocol/openid-connect/certs

dnsNameOuter: test-apps02.konturlabs.com
alertingTime: 10m

otlpTracesExporter: otlp
otlpTracesPort: 4317