# DEV values for user-profile-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag: main.7c594d22f9

replicas: 2
envName: dev
databaseHost: milan.k8s-01.kontur.io.

jwtIssuerUri: https://keycloak01.konturlabs.com/auth/realms/dev
jwtJwkSetUri: https://keycloak01.konturlabs.com/auth/realms/dev/protocol/openid-connect/certs

dnsNameOuter: test-apps02.konturlabs.com
alertingTime: 10m

otlpTracesExporter: otlp
otlpTracesPort: 4317