# TEST values for user-profile-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag: main.34fe8c6.1

replicas: 2
envName: test
databaseHost: london.k8s-01.kontur.io.

jwtIssuerUri: https://keycloak01.konturlabs.com/auth/realms/test
jwtJwkSetUri: https://keycloak01.konturlabs.com/auth/realms/test/protocol/openid-connect/certs

dnsNameOuter: test-apps.konturlabs.com
alertingTime: 5m

otlpTracesExporter: otlp
otlpTracesPort: 4317
