# QUICKSTART values for user-profile-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag: release-0.3.5.d6b718e.1
  pullSecretName: nexus8084
  usePullSecret: true

replicas: 1
envName: quickstart
ingressHost: user-profile-api.kontur

createResource:
  defaultSecrets: true
  ingress: true
  prometheusRule: false
  serviceMonitor: false
  deploymentLivenessProbe: true
isOfflineInstallation: true

databaseHost: host.docker.internal

jwtIssuerUri: https://keycloak01.konturlabs.com/auth/realms/dev #TODO keycloak
jwtJwkSetUri: https://keycloak01.konturlabs.com/auth/realms/dev/protocol/openid-connect/certs #TODO keycloak

dnsNameOuter: none #not used due to isOfflineInstallation flag

otlpTracesExporter: none