# QUICKSTART values for disaster-ninja-be.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
envName: quickstart

createResource:
  defaultSecrets: true
  ingress: false
  prometheusRule: false
  serviceMonitor: false
  deploymentLivenessProbe: true

replicas: 1

image:
  be:
    tag: "release-0.20.0.0d79a4c.1"

resources:
  main:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 768Mi
  notifier:
    requests:
      cpu: 0
      memory: 0
    limits:
      memory: 0

keycloakUrl: 'https://keycloak01.konturlabs.com/auth' #TODO keycloak and others
keycloakRealm: dev #TODO keycloak
eventApiUrl: 'https://test-apps02.konturlabs.com/events'
kcApiUrl: 'https://test-api02.konturlabs.com/layers'
layersApiUrl: 'https://test-api02.konturlabs.com/layers/v2'
insightsApiUrl: 'https://test-apps02.konturlabs.com/insights-api'
userProfileApiUrl: 'https://test-apps02.konturlabs.com/userprofile'
tilesHost: 'https://sonic.kontur.io'

notificationsEnabled: false
notificationsFeed: none
notificationsAlertUrlPattern: none
***REMOVED***

alertingTime: 10m

otlpTracesExporter: none
otlpTracesPort: none

java_tool_options: "-XX:MaxRAMPercentage=50 -javaagent:/opentelemetry/opentelemetry-javaagent.jar"