# LOCAL values for disaster-ninja-be.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
envName: local

replicas: 1

image:
  be:
    pullPolicy: IfNotPresent
    tag: latest

keycloakUrl: 'https://keycloak01.konturlabs.com/auth'
keycloakRealm: dev
eventApiUrl: 'https://test-apps02.konturlabs.com/events'
kcApiUrl: 'https://test-api02.konturlabs.com/layers'
layersApiUrl: 'https://test-api02.konturlabs.com/layers/v2'
insightsApiUrl: 'https://test-apps02.konturlabs.com/insights-api'
userProfileApiUrl: 'https://test-apps02.konturlabs.com/userprofile'
tilesHost: 'https://zigzag.kontur.io'

notificationsEnabled: false
notificationsFeed: kontur-public
notificationsAlertUrlPattern: 'https://test-apps-ninja02.konturlabs.com/active/?event=%s'
notificationsSlackWebHook: 'https://hooks.slack.com/services/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'

alertingTime: 10m

otlpTracesExporter: none
otlpTracesPort: 4317