# PROD values for disaster-ninja-be.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
envName: prod

replicas: 2

image:
  be:
    tag: "0.17.0" # this version will be automatically deployed by Flux

keycloakUrl: 'https://keycloak01.kontur.io/auth'
keycloakRealm: kontur
eventApiUrl: 'https://apps.kontur.io/events/'
kcApiUrl: 'https://api.kontur.io/layers'
layersApiUrl: 'https://api.kontur.io/layers/v2'
insightsApiUrl: 'https://apps.kontur.io/insights-api'
userProfileApiUrl: 'https://apps.kontur.io/userprofile/'
tilesHost: 'https://disaster.ninja'

notificationsEnabled: true
notificationsFeed: kontur-public
notificationsAlertUrlPattern: 'https://disaster.ninja/active/?event=%s&utm_source=slack'
***REMOVED***

alertingTime: 2m
