# DEV values for disaster-ninja-be.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
envName: dev

replicas: 1

image:
  be:
    tag: "main.cff9cde.1" # this version will be automatically deployed by Flux

keycloakUrl: 'https://keycloak01.konturlabs.com/auth'
keycloakRealm: dev
eventApiUrl: 'https://test-apps02.konturlabs.com/events'
kcApiUrl: 'https://test-api02.konturlabs.com/layers'
layersApiUrl: 'https://test-api02.konturlabs.com/layers/v2'
insightsApiUrl: 'https://test-apps02.konturlabs.com/insights-api'
userProfileApiUrl: 'https://test-apps02.konturlabs.com/userprofile'
tilesHost: 'https://zigzag.kontur.io'

notificationsEnabled: true
notificationsFeed: kontur-public
notificationsAlertUrlPattern: 'https://test-apps-ninja02.konturlabs.com/active/?event=%s&utm_source=slack'
***REMOVED***

alertingTime: 10m

otlpTracesExporter: otlp
otlpTracesPort: 4317

java_tool_options: "-XX:MaxRAMPercentage=50 -javaagent:/opentelemetry/opentelemetry-javaagent.jar"