# TEST values for disaster-ninja-be.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
envName: test

replicas: 1

image:
  be:
    tag: "0.16.1" #this version will be automatically deployed by Flux

keycloakUrl: 'https://keycloak01.konturlabs.com/auth'
keycloakRealm: 'test'
eventApiUrl: 'https://test-apps.konturlabs.com/events'
kcApiUrl: 'https://test-api.konturlabs.com/layers'
layersApiUrl: 'https://test-api.konturlabs.com/layers/v2'
insightsApiUrl: 'https://test-apps.konturlabs.com/insights-api'
userProfileApiUrl: 'https://test-apps.konturlabs.com/userprofile'
tilesHost: 'https://sonic.kontur.io'

notificationsEnabled: true
notificationsFeed: 'kontur-public'
notificationsAlertUrlPattern: 'https://test-apps-ninja01.konturlabs.com/active/?event=%s&utm_source=slack'
***REMOVED***

alertingTime: 5m