# PROD values for disaster-ninja-be.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
envName: prod

createResource:
  defaultSecrets: false
  ingress: false
  prometheusRule: true
  serviceMonitor: true
  deploymentLivenessProbe: true

replicas: 2

image:
  be:
    tag: "release-0.19.0.f89cda0.1" # this version will be automatically deployed by Flux

keycloakUrl: 'https://keycloak01.kontur.io/auth'
keycloakRealm: kontur
eventApiUrl: 'https://apps.kontur.io/events/'
kcApiUrl: 'https://api.kontur.io/layers'
layersApiUrl: 'https://api.kontur.io/layers/v2'
insightsApiUrl: 'https://apps.kontur.io/insights-api'
userProfileApiUrl: 'https://apps.kontur.io/userprofile/'
tilesHost: 'https://disaster.ninja'

notificationsEnabled: true
notificationsFeed: kontur-public
notificationsAlertUrlPattern: 'https://disaster.ninja/active/?event=%s&utm_source=slack'
notificationsSlackWebHook: 'https://hooks.slack.com/services/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'

alertingTime: 2m

otlpTracesExporter: otlp
otlpTracesPort: 4317

java_tool_options: "-XX:MaxRAMPercentage=50 -javaagent:/opentelemetry/opentelemetry-javaagent.jar"