apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.envName }}-disaster-ninja-fe
  namespace: {{ .Values.envName }}-disaster-ninja-fe
  labels:
    app.kubernetes.io/name: disaster-ninja-fe
    app.kubernetes.io/instance: {{ .Values.envName }}-disaster-ninja-fe
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.envName }}-disaster-ninja-fe-tls
  issuerRef:
    name: letsencrypt-staging #TODO use letsencrypt-production once tested!
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: {{ .Values.envName }}-disaster-ninja-fe
  dnsNames:
    - {{ .Values.dnsName1 }}
      #TODO add dnsName2 like 'test-ninja02.konturlabs.com'
---
