apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.envName }}-disaster-ninja-fe
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: disaster-ninja-fe
    app.kubernetes.io/instance: {{ .Values.envName }}-disaster-ninja-fe
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  appconfig-cfgmap-data: |
    {{ printf "%s%s%s" "values/appconfig/" .Values.envName ".json" | .Files.Get | indent 4 | trim }}
  nginx-config: |
    {{ "values/nginx/nginx.conf" | .Files.Get | indent 4 | trim }}
---
