apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.envName }}-disaster-ninja-fe
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: disaster-ninja-fe
    app.kubernetes.io/instance: {{ .Values.envName }}-disaster-ninja-fe
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: disaster-ninja-fe
      app.kubernetes.io/instance: {{ .Values.envName }}-disaster-ninja-fe
      #don't add app.kubernetes.io/version
      app.kubernetes.io/managed-by: "Helm"
      stage: {{ .Values.envName }}
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: disaster-ninja-fe
        app.kubernetes.io/instance: {{ .Values.envName }}-disaster-ninja-fe
        app.kubernetes.io/version: {{ .Chart.Version }}
        app.kubernetes.io/managed-by: "Helm"
        stage: {{ .Values.envName }}
      annotations:
        meta.helm.sh/release-name: {{ .Release.Name }}
        meta.helm.sh/release-namespace: {{ .Release.Namespace }}
        rollme: {{ randAlphaNum 5 | quote }} #random value that makes Helm restart pods on any upgrade
    spec:
      containers:
        - name: nginx
          imagePullPolicy: Always #don't use Always for local minikube - otherwise it reloads from remote each time
          image: {{ .Values.image.fe.repository }}:{{ .Values.image.fe.tag | default .Chart.AppVersion }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/active/config
              readOnly: true
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d
              readOnly: true
          readinessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 1
            periodSeconds: 30
            initialDelaySeconds: 10
            timeoutSeconds: 1 #(default)
        - name: nginx-prometheus-exporter
          imagePullPolicy: Always
          image: nginx/nginx-prometheus-exporter:0.10.0
          ports:
            - containerPort: 9113
              name: metrics
          args:
            - -nginx.scrape-uri=http://127.0.0.1:80/stub_status
      dnsPolicy: Default
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.envName }}-disaster-ninja-fe
            items:
              - key: appconfig-cfgmap-data
                path: "appconfig.js"
        - name: nginx-config-volume
          configMap:
            name: {{ .Values.envName }}-disaster-ninja-fe
            items:
              - key: nginx-config
                path: "nginx.conf"
---
