# DEV values for event-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag: "master.44a0248.1"
  pullSecretName: none
  usePullSecret: false

replicas: 1
envName: dev
ingressHost: dev-event-api.k8s-01.konturlabs.com

createResource:
  defaultSecrets: false
  ingress: true
  prometheusRule: true
  serviceMonitor: true
  deploymentLivenessProbe: false

databaseHost: marvin-2022081800.cpgzwvbl4mna.eu-central-1.rds.amazonaws.com
databaseUser: event_api_user01
databaseName: event_api
databasePort: 5432

alertingTime: 10m

jwtIssuerUri: https://keycloak01.konturlabs.com/auth/realms/dev
jwtJwkSetUri: https://keycloak01.konturlabs.com/auth/realms/dev/protocol/openid-connect/certs

profiles: dev

otlpTracesExporter: otlp
otlpTracesPort: 4317

konturApiUrl: 'https://test-api02.konturlabs.com/'

konturAppsUrl: 'https://test-apps02.konturlabs.com/'

pdcUrl: 'https://testdisasteraware.pdc.org'
pdcMapSrvUrl: 'https://testapps.pdc.org'
pdcUser: 'eventapi'

staticdataS3Folder: 'TEST DEV/'

humanitarianCrisisS3Folder: 'kontur_events/TEST DEV/'

awsSqsUrl: 'https://sqs.us-west-1.amazonaws.com/001426858141/SNS_messages_from_pdc-test-publiccloud-sns.fifo'
awsSqsDlqUrl: 'https://sqs.us-west-1.amazonaws.com/001426858141/SNS_messages_from_pdc-test-publiccloud-sns_DLQ.fifo'
awsSqsEnabled: true

feignUserAgent: 'Event API DEV'
