apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/user-profile-api
namePrefix: prod-
namespace: prod-user-profile-api
patches:
  - target:
      kind: HelmRelease
      name: user-profile-api
      group: helm.toolkit.fluxcd.io
      version: v2beta1
    patch: |-
      - op: replace
        path: /spec/chart/spec/valuesFiles
        value:
          - ./helm/user-profile-api/values.yaml
          - ./helm/user-profile-api/values/values-prod.yaml
---