---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: insights-api
spec:
  suspend: false
  interval: 5m
  chart:
    spec:
      chart: ./helm/insights-api
      valuesFiles:
        - ./helm/insights-api/values.yaml
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: kontur-platform
        namespace: flux-system
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
---