{{ if .Values.createDefaultSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.envName }}-isochrone-api
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: isochrone-api
    app.kubernetes.io/instance: {{ .Values.envName }}-isochrone-api
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ= # = 'password'
---
{{ end }}