apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: event-api-db
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/name: event-api-db
    app.kubernetes.io/part-of: event-api
spec:
  backups:
    pgbackrest:
      image: 'registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.40-1'
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 100Gi
  # image: 'nexus.kontur.io:8084/konturdev/crunchy-postgres-gis:test'
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
      name: instance01
      replicas: 2
      resources:
        limits:
          memory: 24Gi
          cpu: '3'
        requests:
          memory: 24Gi
          cpu: '2'
  # 32Gi => 43m
  # 24Gi => 44m
  # 20Gi => fail at 30m
  # 18 Gi => fail at 28m
  # 22 Gi => fail at 31m
  # 23 Gi => fail at 31m
  metadata:
    labels:
      app.kubernetes.io/component: database
      app.kubernetes.io/managed-by: pgo
      app.kubernetes.io/name: event-api-db
      app.kubernetes.io/part-of: event-api
  postGISVersion: '3.2'
  postgresVersion: 14
  users:
    - name: postgres
    - name: event-api
      databases:
        - event-api
      options: SUPERUSER