apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.envName }}-raster-tiler
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: raster-tiler
    app.kubernetes.io/instance: {{ .Values.envName }}-raster-tiler
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: backend
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      #don't add app.kubernetes.io/version
      app.kubernetes.io/name: raster-tiler
      app.kubernetes.io/instance: {{ .Values.envName }}-raster-tiler
      app.kubernetes.io/component: backend
      stage: {{ .Values.envName }}
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: raster-tiler
        app.kubernetes.io/instance: {{ .Values.envName }}-raster-tiler
        app.kubernetes.io/managed-by: "Helm"
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: backend
        stage: {{ .Values.envName }}
      annotations:
        meta.helm.sh/release-name: {{ .Release.Name }}
        meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    spec:
      {{ if .Values.image.usePullSecret }}
      imagePullSecrets: #TODO remove once image is on ghcr.io
        - name: {{ .Values.image.pullSecretName }}{{ end }}
      containers:
        - name: raster-tiler-server
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.port }}
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              memory: {{ .Values.resources.limits.memory | quote }}
              cpu: {{ .Values.resources.limits.cpu | quote }}
          env:
            - name: BASE_URL
              value: {{ .Values.base_url }}
            - name: TITILER_BASE_URL
              value: {{ .Values.titiler_url }}
            - name: DB_POOL_SIZE
              value: {{ .Values.db_pool_size | quote }}
            - name: TILES_CACHE_DIR_PATH
              value: /tiles
            - name: PORT
              value: {{ .Values.port | quote }}
            - name: PGDATABASE
              value: {{ .Values.pg_database }}
            - name: PGHOST
              value: {{ .Values.pg_host }}
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envName }}-raster-tiler
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envName }}-raster-tiler
                  key: password
            {{ if .Values.db_disable_ssl }}
            - name: DB_DISABLE_SSL
              value: "true"
            {{ end }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 1
            periodSeconds: 15
            initialDelaySeconds: {{ .Values.probeInitialDelaySeconds }}
          {{ if .Values.createResource.deploymentLivenessProbe }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 10
            periodSeconds: 15
            initialDelaySeconds: {{ .Values.probeInitialDelaySeconds }}
          {{ end }}
          volumeMounts:
            - mountPath: /tiles
              name: raster-tiler-storage-vol
              readOnly: false
      volumes:
        - name: raster-tiler-storage-vol
          persistentVolumeClaim:
            claimName: {{ .Values.envName }}-raster-tiler
      dnsConfig:
        options:
          - name: ndots
            value: "0"
