{{ if .Values.createResource.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.envName }}-raster-tiler
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: raster-tiler
    app.kubernetes.io/instance: {{ .Values.envName }}-raster-tiler
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: backend
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    cert-manager.io/cluster-issuer: letsencrypt-production #use letsencrypt-staging for testing
    acme.cert-manager.io/http01-edit-in-place: "true" #required otherwise ACME challenge can't be completed
    {{ if .Values.isOfflineInstallation }}
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{ end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingressHost }}
      secretName: {{ .Values.envName }}-raster-tiler-tls # < cert-manager will store the created certificate in this secret.
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingressHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.envName }}-raster-tiler
                port:
                  name: http
{{ end }}
