{{ if .Values.createResource.defaultSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.envName }}-raster-tiler
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: raster-tiler
    app.kubernetes.io/instance: {{ .Values.envName }}-raster-tiler
    app.kubernetes.io/managed-by: "Helm"
    stage: {{ .Values.envName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  username: bW9zYWlj # = mosaic
***REMOVED***
---
{{ end }}