apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/disaster-ninja
namePrefix: dev-
namespace: dev-disaster-ninja
patchesStrategicMerge:
  - helmrelease-be.yaml
  - helmrelease-fe.yaml
---