apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/disaster-ninja
namePrefix: dev-
namespace: dev-disaster-ninja
patches:
  - target:
      kind: HelmRelease
      name: disaster-ninja-.*
      group: helm.toolkit.fluxcd.io
      version: v2beta1
    patch: |-
      - op: replace
        path: /spec/chart/spec/valuesFiles
        value:
          - values.yaml
          - values/values-dev.yaml
---