# Default values for event-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag: latest
  name: nexus.kontur.io:8085/konturdev/event-api

port: 8624
replicas: 1
envName: local
databaseHost: docker.for.mac.host.internal
databaseUser: event_api_user01
databaseName: event-api
databasePort: 5432

alertingTime: 10m

jwtIssuerUri: https://keycloak01.konturlabs.com/auth/realms/test
jwtJwkSetUri: https://keycloak01.konturlabs.com/auth/realms/test/protocol/openid-connect/certs

otlpTracesExporter: none
otlpTracesPort: 4317

konturApiUrl: 'https://test-api.konturlabs.com/'

konturAppsUrl: 'https://test-apps.konturlabs.com/'

pdcUrl: 'https://testdisasteraware.pdc.org'
pdcMapSrvUrl: 'https://testapps.pdc.org'

staticdataS3Folder: 'TEST DEV/'

humanitarianCrisisS3Folder: 'kontur_events/TEST DEV/'

awsSqsEnabled: false

feignUserAgent: 'Event API DEV'
