# DEV values for insights-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag: "11842-indicator-updating-process.e69a304.1"
  tagType: ""
  pullSecretName: none
  usePullSecret: false

replicas: 2
envName: dev
ingressHost: dev-insights-api.k8s-01.konturlabs.com

createResource:
  defaultSecrets: false
  ingress: true
  prometheusRule: true
  serviceMonitor: true
  deploymentLivenessProbe: false

resources:
  app:
    requests:
      cpu: 1
      memory: 5Gi
    limits:
      memory: 7Gi
  redis:
    requests:
      cpu: 100m
      memory: 512M
    limits:
      memory: 1G

databaseHost: ep-twilight-cake-951994.cloud.neon.tech
#databaseHost: milan.k8s-01.kontur.io.
databaseName: main
databaseUsername: insights_api_user01
#databaseName: insights-api
#databaseUsername: insights-api
databasePort: 5432
jmxEnabled: true

dnsNameOuter: test-apps02.konturlabs.com
alertingTime: 10m

keycloakUrl: 'https://keycloak01.konturlabs.com/auth'
keycloakRealm: dev

otlpTracesExporter: otlp
otlpTracesPort: 4317

client_max_body_size: 5g