# TEST values for insights-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag: "11838-add-logger-for-test.66d52d868e4c0f44220d3bada697aa75acbd1d59.1"
  tagType: ""

replicas: 2
envName: test
databaseHost: london.k8s-01.kontur.io.
databasePort: 5432
jmxEnabled: true

dnsNameOuter: test-apps.konturlabs.com
alertingTime: 5m

otlpTracesExporter: otlp
otlpTracesPort: 4317

client_max_body_size: 5g