# TEST values for insights-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag: "release-0.16.3.de955d0.1"
  tagType: ""

replicas: 2
envName: test
databaseHost: london.k8s-01.kontur.io.
databasePort: 5432
jmxEnabled: true

dnsNameOuter: test-apps.konturlabs.com
alertingTime: 5m

keycloakUrl: 'https://keycloak01.konturlabs.com/auth'
keycloakRealm: 'test'

otlpTracesExporter: otlp
otlpTracesPort: 4317

client_max_body_size: 5g