# PROD values for insights-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag: "release-0.16.3.de955d0.1"
  tagType: ""
  pullSecretName: none
  usePullSecret: false

replicas: 2
envName: prod

createResource:
  defaultSecrets: false
  ingress: true
  prometheusRule: true
  serviceMonitor: true
  deploymentLivenessProbe: true

resources:
  app:
    requests:
      cpu: 1
      memory: 4700Mi
    limits:
      memory: 9Gi
  redis:
    requests:
      cpu: 100m
      memory: 512M
    limits:
      memory: 1G

databaseHost: paris.k8s-01.kontur.io.
databasePort: 5432
jmxEnabled: false

dnsNameOuter: apps.kontur.io
alertingTime: 2m

keycloakUrl: 'https://keycloak01.kontur.io/auth'
keycloakRealm: kontur

otlpTracesExporter: otlp
otlpTracesPort: 4317

client_max_body_size: 5g