apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/raster-tiler
namePrefix: prod-
namespace: prod-raster-tiler
patches:
  - target:
      kind: HelmRelease
      name: raster-tiler
      group: helm.toolkit.fluxcd.io
      version: v2beta1
    patch: |-
      - op: replace
        path: /spec/chart/spec/valuesFiles
        value:
          - ./helm/raster-tiler/values.yaml
          - ./helm/raster-tiler/values/values-prod.yaml
---
