# PROD values for layers-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  tag: release-1.9.1.96f6375.1

replicas: 2
envName: prod
createDefaultSecrets: false
databaseHost: paris.k8s-01.kontur.io
dnsNameOuter: api.kontur.io

jwtIssuerUri: 'https://keycloak01.kontur.io/auth/realms/kontur'
jwtJwkSetUri: 'https://keycloak01.kontur.io/auth/realms/kontur/protocol/openid-connect/certs'

alertingTime: 2m

otlpTracesExporter: otlp
otlpTracesPort: 4317
