# DEV values for layers-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  tag: 12935-remove-hardcoded-256-tilesize-in-dn-be-and-allow-to-specify-it-from-layers-db.7dfaaaa.1

replicas: 2
envName: dev
databaseHost: milan.k8s-01.kontur.io
dnsNameOuter: test-api02.konturlabs.com

jwtIssuerUri: 'https://keycloak01.konturlabs.com/auth/realms/dev'
jwtJwkSetUri: 'https://keycloak01.konturlabs.com/auth/realms/dev/protocol/openid-connect/certs'

alertingTime: 10m

otlpTracesExporter: otlp
otlpTracesPort: 4317
