# DEV values for layers-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  tag: 8571-update-dn2-backend-to-utilize-layers-management-api-for-osm-layers.2c741eb.1
  usePullSecret: false
  pullSecretName: none

replicas: 2
envName: dev
ingressHost: dev-layers-api.k8s-01.konturlabs.com

createResource:
  defaultSecrets: false
  ingress: true
  prometheusRule: true
  serviceMonitor: true
  deploymentLivenessProbe: true
isOfflineInstallation: false
probeInitialDelaySeconds: 15

databaseHost: milan.k8s-01.kontur.io

jwtIssuerUri: 'https://keycloak01.konturlabs.com/auth/realms/dev'
jwtJwkSetUri: 'https://keycloak01.konturlabs.com/auth/realms/dev/protocol/openid-connect/certs'

alertingTime: 10m

otlpTracesExporter: otlp
otlpTracesPort: 4317
