# QUICKSTART values for layers-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  tag: release-1.9.1.96f6375.1
  usePullSecret: true
  pullSecretName: nexus8084

replicas: 1
envName: quickstart
ingressHost: layers-api.kontur

createResource:
  defaultSecrets: true
  ingress: true
  prometheusRule: false
  serviceMonitor: false
  deploymentLivenessProbe: true
isOfflineInstallation: true
probeInitialDelaySeconds: 90

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 768Mi

databaseHost: host.docker.internal

jwtIssuerUri: 'http://keycloak.kontur/auth/realms/quickstart'
jwtJwkSetUri: 'http://keycloak.kontur/auth/realms/quickstart/protocol/openid-connect/certs'

alertingTime: 10m

otlpTracesExporter: none
otlpTracesPort: 4317
