# Dev values for raster-tiler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag: latest


replicas: 1
envName: dev
base_url: https://dev-raster-tiler.k8s-01.konturlabs.com
titiler_url: https://test-apps02.konturlabs.com/titiler/
pg_host: milan.k8s-01.kontur.io
storage_size: 100Gi
db_pool_size: "16"
