# Prod values for raster-tiler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag: 1de589209460c0cc1300eb1e8a60edab0822e244


replicas: 1
envName: prod
base_url: https://prod-raster-tiler.k8s-01.konturlabs.com
pg_host: paris.k8s-01.kontur.io
titiler_url: https://apps.kontur.io/titiler/
storage_size: 500Gi
db_pool_size: 16
