# QUICKSTART values for raster-tiler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag: latest
  pullSecretName: nexus8084
  usePullSecret: true

db_disable_ssl: true
replicas: 1
envName: quickstart
base_url: https://localhost #TODO
titiler_url: https://test-apps02.konturlabs.com/titiler/ #TODO
pg_host: host.docker.internal
storage_size: 5Gi
storageClass: standard
db_pool_size: 4

createResource:
  ingress: false
  defaultSecrets: true
  deploymentLivenessProbe: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1
    memory: 768Mi
