# Default values for isochrone-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag: develop.f1ce4f86bbc7ad8ed1cfbab87af2cef6b1fb6389.1
  name: nexus.kontur.io:8084/konturdev/isochrone-api
  pullSecretName: nexus8084
  usePullSecret: true

port: 8614
replicas: 1
envName: quickstart

createResource:
  defaultSecrets: true
  ingress: false
  prometheusRule: false
  serviceMonitor: false
  deploymentLivenessProbe: true

databaseHost: host.docker.internal
databasePort: 5432
alertingTime: 10m

hikari:
  maximumPoolSize: 5
  minimumIdle: 2

populationApiUrl: http://quickstart-insights-api.quickstart-insights-api.svc.cluster.local/insights-api/ #TODO test
calculationWorkersNumber: 3
isochroneTimeLimitSeconds: 1200
isochroneIntervalSeconds: 300
enabledIsochroneProfiles: car

otlpTracesExporter: none
otlpTracesPort: none