# PROD values for isochrone-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag: 0.0.1-SNAPSHOT

replicas: 2
envName: prod
databaseHost: mustang.kontur.io

dnsNameOuter: apps.kontur.io
alertingTime: 2m

hikari:
  maximumPoolSize: 10
  minimumIdle: 3

populationApiUrl: https://apps.kontur.io/insights-api/
calculationWorkersNumber: 7
isochroneTimeLimitSeconds: 1200
isochroneIntervalSeconds: 300
enabledIsochroneProfiles: foot,bicycle,motorbike,car,emergency,

otlpTracesExporter: none
otlpTracesPort: 4317