# LOCAL values for isochrone-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag: latest
  name: nexus.kontur.io:8084/konturdev/isochrone-api
  pullSecretName: nexus8084
  usePullSecret: true

port: 8614
replicas: 1
envName: local
ingressHost: none

createResource:
  defaultSecrets: false
  ingress: false
  prometheusRule: false
  serviceMonitor: false
  deploymentLivenessProbe: false
isOfflineInstallation: false
probeInitialDelaySeconds: 15

databaseHost: host.docker.internal
databasePort: 5432
alertingTime: 10m

hikari:
  maximumPoolSize: 5
  minimumIdle: 2

populationApiUrl: https://test-apps02.konturlabs.com/insights-api/
calculationWorkersNumber: 3
isochroneTimeLimitSeconds: 1200
isochroneIntervalSeconds: 300
enabledIsochroneProfiles: car

otlpTracesExporter: none
otlpTracesPort: none