# PROD values for isochrone-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag: develop.f1ce4f86bbc7ad8ed1cfbab87af2cef6b1fb6389.1
  pullSecretName: none
  usePullSecret: false

replicas: 1
envName: prod

createResource:
  defaultSecrets: false
  ingress: true
  prometheusRule: true
  serviceMonitor: true
  deploymentLivenessProbe: true

databaseHost: mustang.kontur.io

dnsNameOuter: apps.kontur.io
alertingTime: 2m

hikari:
  maximumPoolSize: 10
  minimumIdle: 3

populationApiUrl: https://apps.kontur.io/insights-api/
calculationWorkersNumber: 7
isochroneTimeLimitSeconds: 1200
isochroneIntervalSeconds: 300
enabledIsochroneProfiles: motorbike,car

otlpTracesExporter: otlp
otlpTracesPort: 4317