apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - epig
  # - event-api-db/overlays/DEV
  - event-api-db/overlays/TEST
  - event-api
  - insights-api
#  - isochrone-api
  - layers-api
  - layers-tiles-api
  - osrm
  - raster-tiler
  - titiler
  - user-profile-api
  - disaster-ninja