bases:
  - ../../base
namespace: dev-event-api

generatorOptions:
  disableNameSuffixHash: true

# secretGenerator:
# - name: db-event-api-pgo-s3-credentials
#   files:
#   - s3.conf
#   options:
#     labels:
#       app.kubernetes.io/component: database
#       app.kubernetes.io/managed-by: manually
#       app.kubernetes.io/name: db-event-api
#       app.kubernetes.io/part-of: event-api