apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: db-event-api
spec:
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          auto_explain.log_min_duration: 100s
          log_error_verbosity: verbose
          archive_command: 'pgbackrest --stanza=db archive-push "%p" &>> /pgdata/pg14/log/archive_command.txt'
          restore_command: 'pgbackrest --stanza=db archive-get %f "%p" &>> /pgdata/pg14/log/restore_command.txt'