# see https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/backups/#using-s3

- op: add
  path: /spec/backups/pgbackrest/global
  value:
    # use /pgbackrest/$NAMESPACE/$CLUSTER_NAME/repoN
    repo2-path: /pgbackrest/dev-event-api/db-event-api/repo2

- op: add
  path: /spec/backups/pgbackrest/repos/1
  value:
    name: repo2
    s3:
      bucket: k8s-01-kontur-io--pgbackrest-backups
      endpoint: s3.eu-central-1.amazonaws.com
      region: eu-central-1

- op: add
  path: /spec/backups/pgbackrest/configuration
  value:
    - secret:
        name: db-event-api-pgo-s3-credentials

- op: add
  path: /spec/backups/pgbackrest/manual
  value:
    repoName: repo2
    options:
      - '--type=full'